language: cpp
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - xorg-dev
      - libgl1-mesa-dev
      - libgtk-3-dev
    packages:
      - gcc-7
      - g++-7
script:
 - export CC=gcc-7 ;
 - export CXX=g++-7 ;
 - mkdir build && cd build && cmake .. && cmake --build .
